/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarysystem1;
import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author nikhi
 */
public class Bookstats extends javax.swing.JFrame {

    /**
     * Creates new form Bookstats
     */
    public Bookstats() {
        initComponents();
        loadStats();
    }
    private void loadStats() {
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root", "");

        // Total Books
        PreparedStatement pst1 = con.prepareStatement("SELECT COUNT(*) AS TOTAL FROM books");
        ResultSet rs1 = pst1.executeQuery();
        if (rs1.next()) {
            int totalBooks = rs1.getInt("TOTAL");
            TB.setText(String.valueOf(totalBooks));
        }

        // Number of Books Issued (active issues where return_date is null)
        PreparedStatement pst2 = con.prepareStatement("SELECT COUNT(*) FROM Transactions WHERE RETURNED_DATE IS NULL");
        ResultSet rs2 = pst2.executeQuery();
        if (rs2.next()) {
            BI.setText(rs2.getString(1));
        }

        // Number of Overdue Returns (due_date < current_date and return_date is null)
        PreparedStatement pst3 = con.prepareStatement("SELECT COUNT(*) FROM Transactions WHERE DUE_DATE < CURDATE() AND RETURNED_DATE IS NULL");
        ResultSet rs3 = pst3.executeQuery();
        if (rs3.next()) {
            OR.setText(rs3.getString(1));
        }

        // Most Issued Book
        PreparedStatement pst4 = con.prepareStatement("SELECT NAME FROM books ORDER BY BORROWED DESC LIMIT 1");
        ResultSet rs4 = pst4.executeQuery();
        if (rs4.next()) {
            MIB.setText(rs4.getString(1));
        }

        con.close();

    } catch (Exception e) {
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OR = new javax.swing.JLabel();
        BI = new javax.swing.JLabel();
        TB = new javax.swing.JLabel();
        MIB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OR.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        OR.setForeground(new java.awt.Color(255, 255, 255));
        OR.setText("HELLO");
        getContentPane().add(OR, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 270, 40));

        BI.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        BI.setForeground(new java.awt.Color(255, 255, 255));
        BI.setText("HELLO");
        getContentPane().add(BI, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 270, 50));

        TB.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TB.setForeground(new java.awt.Color(255, 255, 255));
        TB.setText("HELLO");
        getContentPane().add(TB, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 270, 50));

        MIB.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        MIB.setForeground(new java.awt.Color(255, 255, 255));
        MIB.setText("HELLO");
        getContentPane().add(MIB, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 450, 130));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Books");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 220, 80));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BOOKS ISSUED");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("OVERDUE RETURNS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MOST ISSUED BOOK");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem1/pngtree-an-old-bookcase-in-a-library-picture-image_2760144.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Stats().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bookstats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bookstats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bookstats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bookstats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookstats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BI;
    private javax.swing.JLabel MIB;
    private javax.swing.JLabel OR;
    private javax.swing.JLabel TB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
